export enum RoutePath {
  launch = '/',
  login = '/login',
  tooManyDevices = '/login/too-many-devices',
  main = '/main',
  redeemVoucher = '/main/voucher/redeem',
  voucherSuccess = '/main/voucher/success',
  timeAdded = '/main/time-added',
  setupFinished = '/main/setup-finished',
  settings = '/settings',
  selectLanguage = '/settings/language',
  accountSettings = '/settings/account',
  preferences = '/settings/preferences',
  advancedSettings = '/settings/advanced',
  wireguardSettings = '/settings/advanced/wireguard',
  openVpnSettings = '/settings/advanced/openvpn',
  splitTunneling = '/settings/advanced/split-tunneling',
  support = '/settings/support',
  selectLocation = '/select-location',
  filterByProvider = '/select-location/filter-by-provider',
}
